[build-system]
requires      = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "wspace"
version = "0.1.0"
readme = "README.md"
description = "Task Management for every project"
authors = [{ name = "Happer", email = "happer64bit@gmail.com" }]

